config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  scope "(:locale)", locale: /en/ do
    root "users#index"
    get "admins/dashboard"
    resources :users
    resources :restaurants
    resources :dailies
  end
  get "auth/:provider/callback", to: "api/sessions#google_auth"
  get "auth/check", to: "api/sessions#is_authenticated"
  post "auth/logout", to: "api/sessions#destroy"
  get "cross", to: "api/sessions#cross"
  get "food/list", to: "api/foods#index"
  post "/submit-order", to: "api/foods#save"
  put "user/update", to: "api/users#update"
  post "upload-avatar", to: "api/users#avatar"
  post "add-favourite", to: "api/foods#add_favorite"
  post "remove-favourite", to: "api/foods#remove_favorite"
  post "comment/create", to: "api/comments#save"
  get "comment/index", to: "api/comments#index"
  put "comment/update", to: "api/comments#update"
  post "comment/destroy", to: "api/comments#destroy"
  namespace "api", :as => "api" do
    get "auth/failure", to: redirect("/")
    get "auth/login", to: "sessions#login"
    delete "signout", to: "sessions#destroy", as: "signout"
  end
end

app/views/shared/_admin_header.html.erb
<header role="banner">
  <h1><%= t "admin_panel" %></h1>
  <ul class="utilities">
    <br>
    <li class="users">
      <%= link_to t("self_account"), edit_admin_registration_path %>
    </li>
    <li class="logout warn">
      <%= link_to t("logout"), destroy_admin_session_path , method: :delete %>
    </li>
  </ul>
</header>

app/views/shared/_admin_sidenav.html.erb
<nav role='navigation'>
  <ul class="main">
    <li class="dashboard">
      <%= link_to t("dashboard"), admins_dashboard_path %>
    </li>
    <li class="edit">
      <%= link_to t("manage_restaurants"), restaurants_path %>
    </li>
    <li class="write">
      <%= link_to t("write_news"), dailies_path %>
    </li>
    <li class="users">
      <%= link_to t("manage_users"), users_path %>
    </li>
    <li class="comments">
      <%= link_to t("ads"), "#" %>
    </li>
  </ul>
</nav>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this object from being saved:</h2>

    <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>