config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  scope "(:locale)", locale: /en/ do
    root "users#index"
    get "admins/dashboard"
    resources :users
    resources :restaurants
    resources :dailies
  end
  get "auth/:provider/callback", to: "api/sessions#google_auth"
  get "auth/check", to: "api/sessions#is_authenticated"
  post "auth/logout", to: "api/sessions#destroy"
  get "cross", to: "api/sessions#cross"
  get "food/list", to: "api/foods#index"
  post "/submit-order", to: "api/foods#save"
  put "user/update", to: "api/users#update"
  post "upload-avatar", to: "api/users#avatar"
  post "add-favourite", to: "api/foods#add_favorite"
  post "remove-favourite", to: "api/foods#remove_favorite"
  post "comment/create", to: "api/comments#save"
  get "comment/index", to: "api/comments#index"
  put "comment/update", to: "api/comments#update"
  post "comment/destroy", to: "api/comments#destroy"
  namespace "api", :as => "api" do
    get "auth/failure", to: redirect("/")
    get "auth/login", to: "sessions#login"
    delete "signout", to: "sessions#destroy", as: "signout"
  end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :foods
  has_many :dailies

  validates :name, presence: true
  validates :address, presence: true

  class << self
    private

    def inheritance_column
      nil
    end
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :find_restaurant, only: %i(show edit update destroy)
  before_action :authenticate_admin!

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new restaurant_params

    if @restaurant.save
      flash[:success] = t("restaurant.start_case") + t("flash.create_success")
      redirect_to @restaurant
    else
      flash[:danger] = t("restaurant.start_case") + t("flash.create_failed")
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @restaurant.update_attributes(restaurant_params)
      flash[:success] = t("restaurant.start_case") + t("flash.update_success")
      redirect_to @restaurant
    else
      flash[:danger] = t("restaurant.start_case") + t("flash.update_failed")
      render :edit
    end
  end

  def destroy
    if @restaurant.destroy
      flash[:success] = t("restaurant.start_case") + t("flash.delete_success")
    else
      flash[:danger] = t("restaurant.start_case") + t("flash.delete_failed")
    end

    redirect_to restaurants_url
  end

  private

  def find_restaurant
    @restaurant = Restaurant.find_by id: params[:id]
    redirect_to restaurants_url unless @restaurant
  end

  def restaurant_params
    params.require(:restaurant).permit :name, :type, :address
  end
end

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |form| %>
  <%= render "shared/error_messages", object: form.object %>

  <%= form.label t "restaurant.name" %>
  <%= form.text_field :name, class: "form-control" %>

  <%= form.label t "restaurant.address" %>
  <%= form.text_field :address, class: "form-control" %>

  <%= form.submit yield(:restaurant_button), class: "btn btn-primary" %>
<% end %>

app/views/restaurants/edit.html.erb
<% provide :restaurant_button, t("restaurant.update_submit") %>
<%= render "shared/admin_header" %>
<%= render "shared/admin_sidenav" %>

<main role="main">
  <h1><%= t "restaurant.edit" %></h1>
  <%= render "form", restaurant: @restaurant %>
  <%= link_to t("show"), @restaurant %> |
  <%= link_to t("back"), restaurants_path %>
</main>

app/views/restaurants/index.html.erb
<% provide :title, t("manage_restaurants") %>
<%= render "shared/admin_header" %>
<%= render "shared/admin_sidenav" %>

<main role="main">
  <h1 class="ml-2"><%= t "manage_restaurants" %></h1>
  <table class="table ml-2">
    <thead>
      <tr>
        <th><%= t "restaurant.name" %></th>
        <th><%= t "restaurant.address" %></th>
        <th colspan="3"><%= t "actions" %></th>
      </tr>
    </thead>
    <tbody>
      <% @restaurants.each do |restaurant| %>
        <tr>
          <td><%= link_to restaurant.name, restaurant %></td>
          <td><%= restaurant.address %></td>
          <td><%= link_to t("show"), restaurant, class: "btn btn-info" %></td>
          <td><%= link_to t("edit"), edit_restaurant_path(restaurant), class: "btn btn-warning" %></td>
          <td>
            <%= link_to t("destroy"),
              restaurant,
              method: :delete,
              data: { confirm: t("confirm") },
              class: "btn btn-danger"
            %>
            </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <%= link_to t("restaurant.new_path"), new_restaurant_path, class: "btn btn-success ml-2" %>
</main>

app/views/restaurants/new.html.erb
<% provide :restaurant_button, t("restaurant.new_submit") %>
<%= render "shared/admin_header" %>
<%= render "shared/admin_sidenav" %>

<main role="main">
  <h1><%= t "restaurant.new" %></h1>
  <%= render "form", restaurant: @restaurant %>
  <%= link_to t("back"), restaurants_path %>
</main>

app/views/restaurants/show.html.erb
<%= render "shared/admin_header" %>
<%= render "shared/admin_sidenav" %>

<main role="main">
	<p><%= @restaurant.name %></p>
	<p><%= @restaurant.address %></p>
	<%= link_to t("edit"), edit_restaurant_path(@restaurant) %> |
	<%= link_to t("back"), restaurants_path %> |
	<%= link_to t("add_daily"), new_daily_path(restaurant_id: @restaurant.id) %>
	<div class="col-md-12">
		<h2>Today Foods</h2>
		<% if @restaurant.foods.any? %>
			<ol>
				<%= render @restaurant.foods %>
			</ol>
		<% end %>
	</div>
</main>