config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  scope "(:locale)", locale: /en/ do
    root "users#index"
    get "admins/dashboard"
    resources :users
    resources :restaurants
    resources :dailies
  end
  get "auth/:provider/callback", to: "api/sessions#google_auth"
  get "auth/check", to: "api/sessions#is_authenticated"
  post "auth/logout", to: "api/sessions#destroy"
  get "cross", to: "api/sessions#cross"
  get "food/list", to: "api/foods#index"
  post "/submit-order", to: "api/foods#save"
  put "user/update", to: "api/users#update"
  post "upload-avatar", to: "api/users#avatar"
  post "add-favourite", to: "api/foods#add_favorite"
  post "remove-favourite", to: "api/foods#remove_favorite"
  post "comment/create", to: "api/comments#save"
  get "comment/index", to: "api/comments#index"
  put "comment/update", to: "api/comments#update"
  post "comment/destroy", to: "api/comments#destroy"
  namespace "api", :as => "api" do
    get "auth/failure", to: redirect("/")
    get "auth/login", to: "sessions#login"
    delete "signout", to: "sessions#destroy", as: "signout"
  end
end

app/models/daily.rb
class Daily < ApplicationRecord
  belongs_to :restaurant
  has_many :daily_foods

  validates :start_time_order, presence: true
  validates :end_time_order, presence: true, date: {after: :start_time_order}

  class << self
    def today
      Daily.find_by date: DateTime.now.to_date
    end
  end
end

app/controllers/dailies_controller.rb
class DailiesController < ApplicationController
  before_action :find_daily, only: %i(show edit update)

  def index
    @dailies = Daily.all
  end

  def new
    @daily = Daily.new
  end

  def create
    @daily = Daily.new daily_params

    if @daily.save
      flash[:success] = t("daily.start_case") + t("flash.create_success")
      redirect_to @daily
    else
      flash[:danger] = t("daily.start_case") + t("flash.create_failed")
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @daily.update_attributes(daily_params)
      flash[:success] = t("daily.start_case") + t("flash.update_success")
      redirect_to @daily
    else
      flash[:danger] = t("daily.start_case") + t("flash.update_failed")
      render :edit
    end
  end

  private

  def find_daily
    @daily = Daily.find_by id: params[:id]
    redirect_to dailies_url unless @daily
  end

  def daily_params
    params.require(:daily).permit :date, :restaurant_id,
      :discount, :start_time_order, :end_time_order
  end
end

app/views/dailies/_form.html.erb
<%= form_for(@daily) do |form| %>
  <%= render "shared/error_messages", object: form.object %>

  <%= form.label t "daily.date" %>
  <%= form.date_field :date, class: "form-control" %>

  <%= form.label t "daily.restaurant" %>
  <%= select("daily",
    "restaurant_id",
    Restaurant.all.collect {|restaurant| [ restaurant.name, restaurant.id ] },
    { include_blank: true },
    class: "form-control")
  %>

  <%= form.label t "daily.discount" %>
  <%= form.number_field :discount, class: "form-control" %>

  <%= form.label t "daily.start_time_order" %>
  <%= form.time_select :start_time_order, class: "form-control" %>

  <%= form.label t "daily.end_time_order" %>
  <%= form.time_select :end_time_order, class: "form-control" %>

  <br/>

  <%= form.submit yield(:daily_button), class: "btn btn-primary" %>
<% end %>

app/views/dailies/edit.html.erb
<% provide :title, t("edit_daily") %>
<% provide :daily_button, t("daily.edit_submit") %>

<%= render "shared/admin_header" %>

<%= render "shared/admin_sidenav" %>

<main role="main">
  <%= render "form", daily: @daily %>
</main>

app/views/dailies/index.html.erb
<% provide :title, t("today_daily") %>

<%= render "shared/admin_header" %>

<%= render "shared/admin_sidenav" %>

<main role="main">
  <%= link_to "Create today's food", new_daily_path, class: "btn btn-primary" %>
</main>

app/views/dailies/new.html.erb
<% provide :title, t("new_daily") %>
<% provide :daily_button, t("daily.new_submit") %>

<%= render "shared/admin_header" %>

<%= render "shared/admin_sidenav" %>

<main role="main">
  <%= render "form", daily: @daily %>
</main>

app/views/dailies/show.html.erb
<%= render "shared/admin_header" %>
<%= render "shared/admin_sidenav" %>

<main role="main" class="container">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Date:</strong>
    <%= @daily.date.to_date %>
  </p>

  <p>
    <strong>Restaurant:</strong>
    <%= @daily.restaurant.name %>
  </p>

  <p>
    <strong>Discount:</strong>
    <%= @daily.discount %>
  </p>

  <p>
    <strong>Start time order:</strong>
    <%= @daily.start_time_order.to_date %>
  </p>

  <p>
    <strong>End time order:</strong>
    <%= @daily.end_time_order.to_date %>
  </p>
  <%= link_to t("edit"), edit_daily_path(@daily) %> |
  <%= link_to t("back"), restaurants_path %>
</main>